// src/app/page.tsx
"use client";

import { Add as AddIcon } from "@mui/icons-material";
import { IconButton } from "@mui/material";
import { BillCard } from "components/BillCard";
import { Navbar } from "components/Navbar";
import { TableHeader } from "components/TableHeader";
import type { NextPage } from "next";
import styles from "./styles.module.scss";

const Home: NextPage = (): JSX.Element => {
  return (
    <div className={styles.page}>
      <h1 className={styles.title}>Contas a Pagar</h1>
      <TableHeader columnLabels={["Nome", "Valor total", "Opções"]} />
      <main className={styles.main}>
        <BillCard name="Boticário" amount={249.99} />
        <BillCard name="Magazine Luiza" amount={899.99} />
        <BillCard name="Cesuca" amount={609.99} />
        <BillCard name="Mercado Pago" amount={609.99} />
        <BillCard name="Mercado Pago" amount={609.99} />
        <BillCard name="Mercado Pago" amount={609.99} />
        <BillCard name="Mercado Pago" amount={609.99} />
        <BillCard name="Mercado Pago" amount={609.99} />
        <BillCard name="Mercado Pago" amount={609.99} />
        <BillCard name="Mercado Pago" amount={609.99} />
        <BillCard name="Mercado Pago" amount={609.99} />
        <BillCard name="Mercado Pago" amount={609.99} />
        <BillCard name="Mercado Pago" amount={609.99} />
        <BillCard name="Mercado Pago" amount={609.99} />
        <BillCard name="Mercado Pago" amount={609.99} />
        <BillCard name="Mercado Pago" amount={609.99} />
        <BillCard name="Mercado Pago" amount={609.99} />
        <BillCard name="Mercado Pago" amount={609.99} />
        <BillCard name="Mega Oferta do Supermercado Rissul" amount={609.99} />
      </main>
      <Navbar />
      <IconButton className={styles.add_bill_button}>
        <AddIcon />
      </IconButton>
    </div>
  );
};

export default Home;

// App.vue
<script lang="ts" setup>
import "./styles/_global.scss";

useHead({
  htmlAttrs: {
    lang: "pt-BR"
  },

  title: "Contas App",

  meta: [
    { name: "author", content: "Rian Oliveira" },
    { name: "description", content: "Meu app de contas." },
    { name: "keywords", content: "vue, nuxtjs" },
  ],
})
</script>

<template>
  <div class="page">
    <h1 class="title">Contas a Pagar</h1>
    <TableHeader :column-labels="['Nome', 'Valor total', 'Opções']" />
    <main class="main">
      <BillCard name="Boticário" :amount="249.99" />
      <BillCard name="Magazine Luiza" :amount="899.99" />
      <BillCard name="Cesuca" :amount="609.99" />
      <BillCard name="Mercado Pago" :amount="609.99" />
      <BillCard name="Mercado Pago" :amount="609.99" />
      <BillCard name="Mercado Pago" :amount="609.99" />
      <BillCard name="Mercado Pago" :amount="609.99" />
      <BillCard name="Mercado Pago" :amount="609.99" />
      <BillCard name="Mercado Pago" :amount="609.99" />
      <BillCard name="Mercado Pago" :amount="609.99" />
      <BillCard name="Mercado Pago" :amount="609.99" />
      <BillCard name="Mercado Pago" :amount="609.99" />
      <BillCard name="Mercado Pago" :amount="609.99" />
      <BillCard name="Mercado Pago" :amount="609.99" />
      <BillCard name="Mercado Pago" :amount="609.99" />
      <BillCard name="Mercado Pago" :amount="609.99" />
      <BillCard name="Mercado Pago" :amount="609.99" />
      <BillCard name="Mercado Pago" :amount="609.99" />
      <BillCard name="Mega Oferta do Supermercado Rissul" :amount="609.99" />
    </main>
    <Navbar />
    <q-btn flat round icon="add" title="Adicionar nova conta" class="add-bill-button" />
  </div>
</template>

<style lang="scss" scoped>
@use "./styles" as *;

.page {
  min-height: 100vh;
  padding: 16px;
}

.title {
  color: $green;
  font-size: 24px;
  font-weight: 500;
  text-align: center;
}

.main {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding-bottom: 112px;
}

.add-bill-button {
  background-color: $green !important;
  border-radius: 100%;
  bottom: 64px;
  padding: 12px;
  color: $white;
  position: fixed;
  right: 16px;
}
</style>
